config/routes.rb
Zlo::Application.routes.draw do
  get "api/commit_activity"
  get "api/commit_clicks"
  get "api/commit_sources"
  match "api/import/post" => 'api#import_one'
  match "api/import/posts" => 'api#import_many'
  match "api/import/interval/:source" => 'api#interval'

  root :controller => 'backwards', :action => 'index'
  match '/page/:page' => 'backwards#index'

  match 'login' => 'user_sessions#new', :as => 'login'
  match 'logout' => 'user_sessions#destroy', :as => 'logout'

  resources :threads, :only => [:new] do
    collection do
      get 'new/to/:src' => 'threads#new', :as => 'foreign_new'
    end
  end
  resources :user_sessions
  resources :users, :constraints => { :id => /.*/ } do
    resources :pazuzus
  end
  resources :posts, :path => 'p' do
    member do
      get :toggle_showhide, :remove, :toggle_like
    end
    collection do
      get :latest
      match 'latest/:number' => 'posts#latest'
    end
  end
  resources :private_messages, :path => 'persmsg'

  resources :loginposts, :only => [:create]

  resources :presentations do
    member do
      get :use, :clone, :make_default
    end
    collection do
      get :edit_local
      get :edit_default
    end
  end

  namespace :admin do
    get 'index' => 'specials#index'
  end

  resources :moderation_actions, :path => 'moder'

  resources :sources, :only => [] do
    member do
      get 'read/:orig_id', :action => 'read_post'
      get 'post_iframe/:orig_id', :action => 'iframe', :as => 'post_iframe'
      get 'instant', :action => 'instant'
      get 'myreplyto/:orig_id', :action => 'my_reply_to', :as => 'my_reply_to'
    end
  end

end

app/models/pazuzu.rb
class Pazuzu < ActiveRecord::Base
  # We should reload all threads after pazuzing somebody; this is handled via touching the user.
  belongs_to :user, :touch => true
  belongs_to :bastard, :class_name => 'User'

  validate do |ban|
    # Check if bastard was specified but not found
    if ban.bastard.blank? && !ban.bastard_name.blank?
      errors.add(:bastard_name, I18n.t('cant_find'))
    # Something should be specified
    elsif ban.bastard.blank? && ban.unreg_name.blank? && ban.host.blank?
      errors.add(:base, I18n.t('cant_ban_nobody'))
    end
  end

  validates_presence_of :user
  validates_uniqueness_of :user_id, :scope => [:user_id, :host, :unreg_name], :message => I18n.t('cant_ban_twice')


  attr_accessor :use_bastard, :use_host, :use_unreg_name
  attr_accessor :bastard_name
  attr_accessible :bastard, :host, :unreg_name, :bastard_name, :use_bastard, :use_host, :use_unreg_name

  # Apply use_* forward
  before_validation do
    self.bastard = nil if use_bastard == '0'
    self.unreg_name = nil if use_unreg_name == '0'
    self.host = nil if use_host == '0'
    true
  end

  #...and backwards
  def init_use
    if persisted?
      @use_bastard = !self.bastard.blank?
      @use_host = !self.host.blank?
      @use_unreg_name = !self.unreg_name.blank?
    else
      @use_bastard = self.unreg_name.blank?
      @use_host = !self.unreg_name.blank?
      @use_unreg_name = !self.unreg_name.blank?
    end
  end

  def bastard_name
    @bastard_name || (bastard.blank? ? nil : bastard.login)
  end

  before_validation do
    self.bastard = User.find_by_login self.bastard_name
  end

  validate do |ban|
    # You can't ban self!
    if !ban.user.blank? && ban.bastard == ban.user
      errors.add(:base, I18n.t('cant_ban_self'))
    end
  end


  # Check if this rule actually bans the post given
  def bans(post)
    return false unless post

    false ||
      ( host.blank? ? false : post.host == host) ||
      ( bastard.nil? ? false : post.author_id == bastard.id ) ||
      ( unreg_name.blank? ? false : post.unreg_name == unreg_name ) ||
    false
  end

  def equals other_pazuzu
    def nml(x)
      x.blank? ? nil : x
    end
    [ nml(other_pazuzu.bastard), nml(other_pazuzu.host), nml(other_pazuzu.unreg_name) ] ==
      [ nml(self.bastard), nml(self.host), nml(self.unreg_name) ]
  end
end

app/controllers/pazuzus_controller.rb
class PazuzusController < ApplicationController
  before_filter :find_user
  before_filter :new_pazuzu_from_params, :only => [:create]
  before_filter :new_pazuzu, :only => [:new]
  before_filter :find_pazuzu, :only => [:destroy,:update,:edit,:show,:clone,:use,:make_default]
  before_filter :find_pazuzus, :except => [:edit_local,:edit_default]

  filter_access_to :create, :new, :show, :delete, :attribute_check => true
  filter_access_to :index, :attribute_check => false

  before_filter :checkboxes_for_pazuzu, :only => [:new, :edit]

  # GET /pazuzus
  # GET /pazuzus.json
  def index
    @pazuzus = Pazuzu.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pazuzus }
    end
  end

  # GET /pazuzus/1
  # GET /pazuzus/1.json
  def show
    @pazuzu = Pazuzu.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pazuzu }
    end
  end

  # GET /pazuzus/new
  # GET /pazuzus/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pazuzu }
    end
  end

  # GET /pazuzus/1/edit
  def edit
  end

  # POST /pazuzus
  # POST /pazuzus.json
  def create
    respond_to do |format|
      if @pazuzu.save
        format.html { redirect_to edit_user_pazuzu_path(@user, @pazuzu), notice: t('notice.pazuzu.created') }
        format.json { render json: @pazuzu, status: :created, location: @pazuzu }
      else
        format.html { render action: "new" }
        format.json { render json: @pazuzu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pazuzus/1
  # PUT /pazuzus/1.json
  def update
    @pazuzu = Pazuzu.find(params[:id])

    respond_to do |format|
      if @pazuzu.update_attributes(params[:pazuzu])
        format.html { redirect_to user_pazuzus_url(@user), notice: t('notice.pazuzu.edited') }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @pazuzu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pazuzus/1
  # DELETE /pazuzus/1.json
  def destroy
    @pazuzu.destroy

    respond_to do |format|
      format.html { redirect_to user_pazuzus_url(@user) }
      format.json { head :ok }
    end
  end

  private
  def find_pazuzu
    @pazuzu = Pazuzu.find(params[:id])
  end
  def find_pazuzus
    @pazuzus = current_user ? current_user.pazuzus : []
  end

  def new_pazuzu_from_params
    if current_user
      @pazuzu = Pazuzu.new(params[:pazuzu])
      @pazuzu.user = current_user
    end
  end

  def new_pazuzu
    @pazuzu = Pazuzu.new({:user => current_user, :bastard_name => params['bastard'], :host => params['post_host'], :unreg_name => params['unreg_name']}, :without_protection => true)
  end

  def checkboxes_for_pazuzu
    @pazuzu.init_use if @pazuzu
  end

  def find_user
    @user = current_user
  end
end

app/views/pazuzus/_form.html.haml
= form_for([@user,@pazuzu]) do |f|
  =error_messages_for @pazuzu.errors, :pazuzu
  -# NOTE: this is not at the post to prevent loading all pazuzus at each post request.  This would take a DB request, which is mostly unnecessary.
  -if @user.pazuzus.any? {|p| p.equals @pazuzu}
    %p.warning=ta(:already_exists,:pazuzu)
  %table
    %tr
      %th
        =t(:criterion).capitalize
      %th
        =t(:value).capitalize
    %tr
      %td
        = f.check_box :use_bastard
        = f.label :bastard
      %td
        = f.text_field :bastard_name
    %tr
      %td
        = f.check_box :use_host
        = f.label :host
      %td
        = f.text_field :host
    %tr
      %td
        = f.check_box :use_unreg_name
        = f.label :unreg_name
      %td
        = f.text_field :unreg_name
  %div.actions
    = f.submit

app/views/pazuzus/_list.html.haml
-if @pazuzus && !@pazuzus.empty?
  %table
    %tr
      %th=ta(:username,:pazuzu)
      %th=ta(:host,:pazuzu)
      %th=t(:action)
    -@pazuzus.each do |p|
      %tr
        %td
          - user_link(p.bastard, p.unreg_name)
        %td
          = p.host
        %td
          (
          =link_to_unless_current ta(:edit,:pazuzu), edit_user_pazuzu_path(@user,p)
          =", "
          = link_to t('Destroy'), [@user,p], confirm: 'Are you sure?', method: :delete
          )

app/views/pazuzus/edit.html.haml
%h1=ta(:edit,:pazuzu)
= render 'form'
%h2=ta(:index,:pazuzu)
= render 'list'

app/views/pazuzus/index.html.haml
%h1=ta(:index,:pazuzu)
= render 'list'

=link_to ta(:create,:pazuzu), new_user_pazuzu_path(@user)

app/views/pazuzus/new.html.haml
%h1=ta(:create,:pazuzu)
= render 'form'
%h2=ta(:index,:pazuzu)
= render 'list'

app/views/pazuzus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @pazuzu.user %>
</p>

<p>
  <b>Bastard:</b>
  <%= @pazuzu.bastard %>
</p>

<p>
  <b>Unreg name:</b>
  <%= @pazuzu.unreg_name %>
</p>

<p>
  <b>Host:</b>
  <%= @pazuzu.host %>
</p>


<%= link_to 'Edit', edit_pazuzu_path(@pazuzu) %> |
<%= link_to 'Back', pazuzus_path %>