config/routes.rb
Zlo::Application.routes.draw do
  get "api/commit_activity"
  get "api/commit_clicks"
  get "api/commit_sources"
  match "api/import/post" => 'api#import_one'
  match "api/import/posts" => 'api#import_many'
  match "api/import/interval/:source" => 'api#interval'

  root :controller => 'backwards', :action => 'index'
  match '/page/:page' => 'backwards#index'

  match 'login' => 'user_sessions#new', :as => 'login'
  match 'logout' => 'user_sessions#destroy', :as => 'logout'

  resources :threads, :only => [:new] do
    collection do
      get 'new/to/:src' => 'threads#new', :as => 'foreign_new'
    end
  end
  resources :user_sessions
  resources :users, :constraints => { :id => /.*/ } do
    resources :pazuzus
  end
  resources :posts, :path => 'p' do
    member do
      get :toggle_showhide, :remove, :toggle_like
    end
    collection do
      get :latest
      match 'latest/:number' => 'posts#latest'
    end
  end
  resources :private_messages, :path => 'persmsg'

  resources :loginposts, :only => [:create]

  resources :presentations do
    member do
      get :use, :clone, :make_default
    end
    collection do
      get :edit_local
      get :edit_default
    end
  end

  namespace :admin do
    get 'index' => 'specials#index'
  end

  resources :moderation_actions, :path => 'moder'

  resources :sources, :only => [] do
    member do
      get 'read/:orig_id', :action => 'read_post'
      get 'post_iframe/:orig_id', :action => 'iframe', :as => 'post_iframe'
      get 'instant', :action => 'instant'
      get 'myreplyto/:orig_id', :action => 'my_reply_to', :as => 'my_reply_to'
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic do |config|
    config.validates_format_of_login_field_options :with => /.*/
  end
  # Login uniqueness
  validates_uniqueness_of :login
  # Since login is unique anyway, redefine the activerecord's auto-generated finder
  # NOTE: we can't use "alias" here, since the method is not created before we connect to DB
  def self.find_by_login(login)
    find_last_by_login(login)
  end

  # Mass-assignment protection
  attr_accessible :password, :password_confirmation, :email, :signature_body

  has_many :private_messages
  has_many :unread_messages, :class_name => 'PrivateMessage', :conditions => {:unread => true}

  attr_accessor :current_password
  attr_accessible :current_password

  attr_accessor :suppress_current_password_check

  # For use in form
  validates_each :current_password do |record, attr, value|
    # Do not try to validate "current_password" if the user's being created
    if record.persisted? && !record.suppress_current_password_check
      record.errors.add attr, I18n.t('is_invalid') unless UserSession.new(:login => record.login, :password => record.current_password).valid?
    end
  end

  # User-readable name
  def name
    login
  end
  # URL id
  def to_param
    login
  end
  def self.from_param(p)
    find_by_login(p)
  end

  # Id for CSS username highlighting
  def to_css_id
    id
  end

  # Roles
  has_and_belongs_to_many :roles
  # required by auth plugin
  def role_symbols
    (roles || []).map {|r| r.name.to_sym}
  end

  before_create do
    # Add default role
    roles << Role.find_or_create_by_name('user') if roles.count == 0
    # Add default presentation
    presentations << Presentation.create if presentations.empty?
  end


  # Presentations
  has_many :presentations
  belongs_to :default_presentation, :class_name => 'Presentation'
  def current_presentation(cookies = {})
    result = nil
    # Try to load the presentation for the current user recorded in cookies
    if presentation_name = cookies[:presentation_name]
      result = presentations.where(['name = ?', presentation_name]).first
    end
    # If we couldn't find a presentation via cookies, just show the default.  We should not show an error here!
    result ||= default_presentation
    result ||= presentations.first
    result or raise "Can't find current presentation for user #{self.login}"
  end

  #Hidden posts
  has_many :hide_actions, :class_name => 'HiddenPostsUsers'
  has_many :hidden_posts, :class_name => 'Posts', :through => :hide_actions
  # Likes
  has_many :likes, :class_name => 'LikeUser'
  has_many :liked_posts, :class_name => 'Posts', :through => :likes

  # Pazuzus
  # (user hiding preferences are named after pazuzu, who was first to create a user script to hide certain users from being showed to you personally)
  has_many :pazuzus

  # HACK!  Convey that we're not using pazuzus!
  attr_accessor :nopazuzu

  # User's posts
  has_many :posts, :class_name => 'Posts'

  # Signature
  belongs_to :signature, :autosave => true, :class_name => 'TextContainer', :foreign_key => 'signature'
  validates_length_of :signature_body, :maximum => 333
  protected
  def ensure_signature
    self.signature ||= TextContainer.make('')
  end
  public
  def signature_body=(x)
    ensure_signature[0] = x
  end
  def signature_body
    ensure_signature.body[0]
  end
  def formatted_signature
    ensure_signature.filtered[0]
  end
  # Belongs_to associations, unlike has_one, need to be saved explicitly
  before_save do
    ensure_signature.save
  end

  # Caching
  def user_roles_key
    current_user ? current_user.roles.map(&:name).join(',') : 'guest'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :find_user, :only => [:show, :update, :edit, :destroy]
  before_filter :load_users, :only => [:index]

  filter_resource_access

  # GET /users
  # GET /users.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    # Mass-assignment protection doesn't allow us to do this.
    @user.login = params[:user][:login]

    respond_to do |format|
      # Do not check captcha on validation failure: user should be able to first complete the form correctly without solving the captcha.
      if @user.valid? && captcha_ok?(:model => @user) && @user.save
        flash[:notice] = 'Registration successful'
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    # TODO: fix permission to declauth check
    @user.suppress_current_password_check = true if current_user.role_symbols.include? :admin
    respond_to do |format|
      if @user.demo
        format.html { redirect_to @user, notice: %Q(You can not edit a demonstration user's settings) }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      elsif @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        @user.current_password = nil
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end

  protected
  def find_user
    # We do not use 'self' to avoid problems with declarative auth
    @user = User.from_param(params[:id]) unless params[:id].blank?
  end
  # Alias for filter_resource_access: it expects "load_user" method rather than find_user.
  alias_method :load_user, :find_user

  def load_users
    @users = User.all
  end
end

app/views/users/_form.html.haml
= form_for(@user) do |f|
  =error_messages_for @user.errors, 'user'
  -if @user.persisted?
    = f.label :login
    = @user.login
    %br/
  -else
    %div.field
      = f.label :login
      = f.text_field :login
  -if @user.persisted?
    %div.field
      = f.label :current_password
      = f.password_field :current_password
  %div.field
    = f.label :password
    = f.password_field :password
  %div.field
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  %div.field
    = f.label :email
    = f.text_field :email
    Write some crap here, no e-mail will be sent anyway!
  %div.field
    = f.label :signature_body
    = f.text_area :signature_body, :cols => 50, :rows => 7
  %div
    =t(:'current_signature', :scope => 'activerecord.attributes.user')
    %br/
    != @user.formatted_signature
  - if !current_user && captcha_enabled
    =t :'recaptcha.prompt'
    = captcha_tags
  %div.actions
    =f.submit

app/views/users/edit.html.haml
%h1=ta('edit','user')
= render 'form'
= link_to t('Back'), root_path

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Login</th>
    <th>Email</th>
    <th>Crypted password</th>
    <th>Password salt</th>
    <th>Persistence token</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.login %></td>
    <td><%= user.email %></td>
    <td><%= user.crypted_password %></td>
    <td><%= user.password_salt %></td>
    <td><%= user.persistence_token %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.haml
%h1=ta('new','user')
= render 'form'
= link_to t('Back'), root_path

app/views/users/show.html.haml
%p{'id'=>'notice'}=notice
%p
  %b=label :user, :login
  =@user.login
%p
  %b=label :user, :email
  =t('Hidden')
-if permitted_to? :create, :private_messages
  %p=link_to ta('write',:private_message), new_private_message_path(:to => @user)
-else
  %p
    = link_to t('Log in'), login_path
    = ta(:log_in_to_write,:private_message)
-if permitted_to? :edit, @user
  =link_to t('Edit'), edit_user_path(@user)