config/routes.rb
Zlo::Application.routes.draw do
  get "api/commit_activity"
  get "api/commit_clicks"
  get "api/commit_sources"
  match "api/import/post" => 'api#import_one'
  match "api/import/posts" => 'api#import_many'
  match "api/import/interval/:source" => 'api#interval'

  root :controller => 'backwards', :action => 'index'
  match '/page/:page' => 'backwards#index'

  match 'login' => 'user_sessions#new', :as => 'login'
  match 'logout' => 'user_sessions#destroy', :as => 'logout'

  resources :threads, :only => [:new] do
    collection do
      get 'new/to/:src' => 'threads#new', :as => 'foreign_new'
    end
  end
  resources :user_sessions
  resources :users, :constraints => { :id => /.*/ } do
    resources :pazuzus
  end
  resources :posts, :path => 'p' do
    member do
      get :toggle_showhide, :remove, :toggle_like
    end
    collection do
      get :latest
      match 'latest/:number' => 'posts#latest'
    end
  end
  resources :private_messages, :path => 'persmsg'

  resources :loginposts, :only => [:create]

  resources :presentations do
    member do
      get :use, :clone, :make_default
    end
    collection do
      get :edit_local
      get :edit_default
    end
  end

  namespace :admin do
    get 'index' => 'specials#index'
  end

  resources :moderation_actions, :path => 'moder'

  resources :sources, :only => [] do
    member do
      get 'read/:orig_id', :action => 'read_post'
      get 'post_iframe/:orig_id', :action => 'iframe', :as => 'post_iframe'
      get 'instant', :action => 'instant'
      get 'myreplyto/:orig_id', :action => 'my_reply_to', :as => 'my_reply_to'
    end
  end

end

app/helpers/posts_helper.rb
# coding: utf-8
# As we work with strings here, we should set encoding for them

require 'markup/boardtags.rb'

module PostsHelper
  def fast_link
    return @_post_fast_link if @_post_fast_link
    # Render a test link with placeholders
    magic = 47382929372 # Beware! should not be equal to a post id!
    pl = link_to 'TITLE_PH', post_path(magic), :name => magic

    # We abuse that, in HTML, link address and anchor name are before the text.
    md = /^(.*)#{magic}(.*)#{magic}(.*)TITLE_PH(.*)$/u.match(pl) or raise "WTF!  how come a link became #{pl} ???"
    md1 = md[1]
    md2 = md[2]
    md3 = md[3]
    md4 = md[4]

    # Note to_s near "id"!  Otherwise, ActiveRecord (or Ruby) will convert it to ASCII instead of UTF-8
    @_post_fast_link = proc {|buf,p,title_override| buf << md1 << p.id.to_s << md2 << p.id.to_s << md3 << (title_override || p.htmlsafe_title.strip) << md4}

  end

  # Only URL, without "<a>" tag
  def fast_post_url
    return @_post_fast_url if @_post_fast_url
    # Render a test link with placeholders
    magic = 47382929372 # Beware! should not be equal to a post id!
    pl = post_path(magic)

    # We abuse that, in HTML, link address and anchor name are before the text.
    md = /^(.*)#{magic}(.*)$/u.match(pl) or raise "WTF!  how come a link became #{pl} ???"
    md1 = md[1]
    md2 = md[2]

    # Note to_s near "id"!  Otherwise, ActiveRecord (or Ruby) will convert it to ASCII instead of UTF-8
    @_post_fast_url = proc {|buf,p| buf << md1 << p.id.to_s << md2}

  end

  def fast_user
    return @_user_fast_link if @_user_fast_link
    # Render a test link with placeholders
    magic = 47382929372 # Beware! should not be equal to a user id!
    pl = link_to 'TITLE_PH', user_path(magic)
    pl.force_encoding('UTF-8')

    # We abuse that, in HTML, link address is before the text.
    md = /^(.*)#{magic}(.*)TITLE_PH(.*)$/u.match(pl)
    # The regexp is unicode, but the match data is ascii (why??)
    md1 = md[1].force_encoding('UTF-8')
    md2 = md[2].force_encoding('UTF-8')
    md3 = md[3].force_encoding('UTF-8')

    @_user_fast_link = proc {|buf,login| buf << md1 << login << md2 << h(login) << md3}

  end

  # We both cache links, and translations, as translating the same string thousands of times takes .05 sec.  The accompanying block should return a pair of values, iftrue and iffalse.
  def fast_hide
    return @_post_fast_hide if @_post_fast_hide
    # Render a test link with placeholders
    magic = 47382929372 # Beware! should not be equal to a post id!
    magic_class = 'MAGIC_ANOTHER_ACTION'
    pl = link_to 'TITLE_PH', toggle_showhide_post_path(magic), :class => "action subthread #{magic_class}"

    # We abuse that, in HTML, link address is before the text.
    md = /^(.*)#{magic}(.*)#{magic_class}(.*)TITLE_PH(.*)$/u.match(pl) or raise "WTF!  how come a link became #{pl} ???"
    md1 = md[1]
    md2 = md[2]
    md3 = md[3]
    md4 = md[4]

    iftrue, iffalse = yield

    # Note to_s near "id"!  Otherwise, ActiveRecord (or Ruby) will convert it to ASCII instead of UTF-8
    @_post_fast_hide = proc do |buf,p,should_hide|
      buf <<
        md1 << p.id.to_s <<
        # Reverse this: should_hide means if we "should hide the subthread"
        md2 << (should_hide ? 'show' : 'hide') <<
        md3 << (should_hide ? iftrue : iffalse) << md4
    end

  end

  # We both cache links, and translations, as translating the same string thousands of times takes .05 sec.  The accompanying block should return a pair of values, iftrue and iffalse.
  def fast_liked
    return @_post_fast_liked if @_post_fast_liked
    # Render a test link with placeholders
    magic = 47382929372 # Beware! should not be equal to a post id!
    magic_class = 'MAGIC_ANOTHER_ACTION'
    pl = link_to 'TITLE_PH', toggle_like_post_path(magic), :class => "like action #{magic_class}"

    # We abuse that, in HTML, link address is before the text.
    md = /^(.*)#{magic}(.*)#{magic_class}(.*)TITLE_PH(.*)$/u.match(pl) or raise "WTF!  how come a link became #{pl} ???"
    md1 = md[1]
    md2 = md[2]
    md3 = md[3]
    md4 = md[4]

    iftrue, iffalse = yield

    # Note to_s near "id"!  Otherwise, ActiveRecord (or Ruby) will convert it to ASCII instead of UTF-8
    @_post_fast_liked = proc do |buf,p,should_liked|
      buf <<
        md1 << p.id.to_s <<
        # Reverse this: should_liked means if we "should liked the subthread"
        md2 << (should_liked ? 'like' : 'dislike') <<
        md3 << (should_liked ? iftrue : iffalse) << md4
    end

  end
  def unless_deleted(post)
    # Cache user's permission to view deleted posts
    if @_can_see_deleted.nil?
      @_can_see_deleted = permitted_to? :see_deleted, :posts
    end
    yield unless !@_can_see_deleted && post.deleted
  end

  # Returns proc that returns if the user name given should be highlighted.  Encapsulates current user and presentation.
  def should_highlight
    return @_should_highlight if @_should_highlight
    # Load settings
    settings_allow = current_presentation.highlight_self
    # Load current user's nickname
    cu = current_user
    cu = cu.to_css_id if cu

    @_should_highlight = proc {|l| settings_allow && (l == cu)}
  end

  def time_for_header(time,tz)
    tz.utc_to_local(time).strftime("%d.%m.%Y %H:%M")
  end

  # Casted after the tree is printed.  Changes the class of the span the current post's header is wrapped, so that it looks differently
  def post_span_replace(tree_string,post,user = current_user)
    user_cssid = user ? user.to_css_id : nil
    # NOTE: I tried to use "provide" instead of "content_for" to avoid unnecessary concatenation, but it didn't work.  Instead, we check if the content has been supplied before printing it. (TODO: check if slow!)
    # If we're not showing any particular post, do not add any styles
    if post && !(content_for? :current_post_style)
      provide :current_post_style, <<EOS
span.css#{post.id} a {
  font-weight: bold;
  color: #000;
  &:visited {}
  &:hover   { color: #000; }
}
EOS
    end

    # Not only we check if the user login is supplied but also if we actually want to highlight it
    if user_cssid && should_highlight[user_cssid] && !(content_for? :current_user_style)
      # NOTE that the CSS classes should coincide with those in user_link function in app/helpers/application_helper.rb
      provide :current_user_style, <<EOS
span.uid#{user_cssid} a {
  font-weight: bold;
  color: red;
}
EOS
    end
    tree_string
  end

  def fast_print_username(buf,post)
    # NOTE: keep this in sync with user_link in application_helper.rb!

    # Due to the speed concerns, we use user_login here instead of user.login, so we don't need to load users
    if this_login = post.user_login
      # Highlight message, if necessary
      # See post_span_replace where the uid is used.
      buf << %Q(<span class="user-other uid#{post.cssid}">)
      fast_user[buf,this_login]
      buf << %Q(</span>)
    else
      buf << %Q(<span class="user-unreg">) << (post.unreg_name || "NIL") << %Q(</span>)
    end
  end

  # Print raw html (no ERB or HAML!) for a line of this post.  User view settings are ignored for now
  def fast_print(post, tz, buf = '', view_opts = {})
    # We'll use string as a "StringBuffer", appending to a mutable string instead of concatenation

    # Some users may view deleted posts (if they're privileged enough).
    # See the closing tag the end of the function
    buf << %Q(<span class="post-deleted">) if post.deleted

    # Post title (link or plain, depending on whether it's the current post)
    # The css class with post.id is used to render the same thread regardless what post is current, making the thread browsing easier.  See post_span_replace for how it works.
    buf << %Q(<span class="post-oneline css#{post.id}">)
    # This already prints to the buf!  Do not append, or your memory will blow!
    fast_link[buf,post]
    buf << %Q(</span>)
    # (url)/(pic) marks
    marks = post.marks.map(&:to_s)
    # If the title contains url, add it to the "url" mark
    url_link = nil
    unless post.follow.blank?
      url_link = post.follow
      marks |= ['url']
    end
    marks.each do |mark|
      if url_link && mark == 'url'
        buf << ' <span class="post-mark">(<a href="' << url_link << '">' << mark << '</a>)</span>'
      else
        buf << ' <span class="post-mark">(' << mark << ")</span>"
      end
    end
    # Now (+)/(-) marks
    if post.empty_body?
      buf << ' (-)'
    else
      if view_opts[:plus]
        # Let's insert a JavaScript "+"!
        buf << %Q( <a class="postbody" id="sh#{post.id}" onclick="pbsh(#{post.id});" href=")
        fast_post_url[buf,post]
        buf << %Q(">(+)</a>)
      end
    end
    # post clicks
    if post.clicks != 0 && post.clicks != '0'
      buf << ' <span class="post-clicks">('
      if post.rating != 0 && post.rating != '0'
        # FIXME: style
        buf << '<b>' << post.rating.to_s << '</b>'
        buf << '/'
      end
      buf << post.clicks.to_s << ")</span>"
    end

    buf << ' - '
    fast_print_username(buf,post)
    buf << " (#{post.host}) "
    buf << ' - '
    buf << %Q(<span class="post-timestamp">) << time_for_header(post.created_at,tz) << %Q(</span>)

    # See the opening tag the end of the function
    buf << %Q(</span>) if post.deleted
  end

  def fast_showhide(post,tree,thread_info,buf = '')
    # Post hidden mark and hide/show modifier
    # NOTE: the attrs to hidden_by are ignored for the FasterPost, but they're left for compatibility with the usual Posts.
    # For FasterPost, :user => current_user has already been applied in the fetching sql, so we do not specify it here
    hidden = post.hidden_by?(:user => current_user, :thread_info => thread_info, :show_all => @show_all_posts) 
    # Because showhide does not have any effect in single-post view, do not display this all
    unless @show_all_posts
      # Unfortunately, we can't use permissions here (until we optimize them)
      buf << ' '

app/views/posts/_button.html.haml
-if btr = BUTTON_REGISTRY[button]
  %button{:type => 'button', :class => 'style', :name => btr[:name], :accesskey => btr[:accesskey], :title => btr[:title], :onclick => btr[:onclick], :tabindex => 5}
    -if btr[:html]
      !=btr[:html]
    -else
      =button

app/views/posts/_form.html.haml
= form_for @post do |f|
  = error_messages_for @post.text_container.errors, :text_container
  = error_messages_for @post.errors, :post
  %table{:border=>0, :cellspacing => 0, :cellpadding => 3}
    %tr
      %td{:colspan => 2, :align => "center"}
        %big
          %a{:name => 'reply'}Post
    %tr
      %td{:colspan => 2}
        %hr{:align => 'center', :width => '80%', :noshade => true}
    %tr
      %td{:align => 'center'}
        %b Name:
      - if current_user
        %td{:align => 'left'}
          %span.postform-login= current_user.login
          %span.postform-logout=link_to 'Log out', logout_path
      - else
        = f.fields_for :session do |sf|
          %td{:align => 'left'}
            =sf.text_field 'login', :size => 22
            %b Password:
            =sf.password_field 'password', :size => 22
            %b Autologin:
            -# Note that this is not "remember me" session attribute.  It's whether we log in or just use the credentials for one-time posting.  Note the f instead of sf!
            =f.check_box 'autologin'
    %tr
      %td{:align => 'center'}Topic:
      %td
        =f.text_field 'title', :size => 88
    %tr
      %td{:colspan => 2, :align => :center}
        =f.text_area 'body', :cols => 75, :rows => 12

  = f.submit t('helpers.submit.posts.preview'), :default => true, :name => :preview
  = f.submit

app/views/posts/_header_line.html.haml
-# Post title (link or plain, depending on whether it's the current post)
-# We strip whitespace from the post's title
- post_title = post.title.strip
- if @post && (post.id == @post.id)
  %span.this-post-oneline
    = post_title
- else
  %span.post-oneline
    = link_to post_title, post_path(post)
- if post.empty_body?
  (-)
- else
  (+)
-# (url)/(pic) marks
- post.marks.each do |mark|
  %span.post-mark="(#{mark}) "
-# post clicks
- if post.clicks != 0
  %span.post-clicks="(#{post.clicks})"
\-
-# Due to the speed concerns, we use user_login here instead of user.login, so we don't need to load users
- if post.user_login
  %span.post-user= link_to post.user_login, user_path(post.user_login)
- else
  %span.post-unreg= (post.unreg_name || "NIL")
="(#{post.host}) "
%span.post-timestamp
  -tz = current_presentation.tz
  = time_for_header(post.created_at, tz)
-# Post Editing link
- if permitted_to? :edit, post
  =link_to t("Edit"), edit_post_path(post)
-# Post hidden mark and hide/show modifier
-hidden = post.hidden_by?(:user => current_user, :thread_hides => thr.hides, :show_all => @show_all_posts)
-kids = thr.build_subtree[post.id]
- if kids && !kids.empty? && permitted_to?(:toggle_showhide, :posts)
  - if hidden
    =link_to t("Show subtree"), toggle_showhide_post_path(post)
  - else
    =link_to t("Hide subtree"), toggle_showhide_post_path(post)

app/views/posts/_loginpost.html.haml
-# the name of the form is used in post.js tag editor!  Do not change!
= form_for @loginpost, :html => {:name => 'postform'} do |f|
  = f.hidden_field :reply_to
  -# Error messages for the validated post
  - if @loginpost.saved_post
    =error_messages_for @loginpost.saved_post.errors, 'posts'
  -# Error messages for the login form
  - if @loginpost.session
    =error_messages_for @loginpost.session.errors, 'session'
  -# Other error messages (are there any?)
  =error_messages_for @loginpost.errors, 'posts'
  -# Now the form itself
  %table{:border=>0, :cellspacing => 0, :cellpadding => 3, :align => 'center'}
    -# Do not show "reply to" if we are creating a new thread
    -if @loginpost.reply_to
      %tr
        %td{:colspan => 2, :align => "center"}
          %big
            %a{:name => 'reply'}=f.label :reply
      %tr
        %td{:colspan => 2}
          %hr{:align => 'center', :width => '80%', :noshade => true}
    %tr
      %td{:align => 'center'}
        %b=f.label :name
      - if current_user
        %td{:align => 'left'}
          %span.postform-login= current_user.login
          %span.postform-logout=link_to t('Log out'), logout_path
      - else
        = f.fields_for :session do |sf|
          %td{:align => 'left'}
            =sf.text_field 'login', :size => 22
            %b=sf.label :password
            =sf.password_field 'password', :size => 22
            %b=f.label :autologin
            -# Note that this is not "remember me" session attribute.  It's whether we log in or just use the credentials for one-time posting.  Note the f instead of sf!
            =f.check_box 'autologin'
    %tr
      %td{:align => 'center'}=f.label :title
      %td
        =f.text_field 'title', :size => 88, :tabindex => 1
    %tr
      %td{:colspan => 2, :class => 'toolbar', :align=>'center'}
        - buttons = [%w(b i u q pic url h s sup sub strike), %w(color red pre center tex tub spoiler hr smile)]
        - buttons.each do |row|
          - row.each do |btn|
            - make_button(btn)
          %br/
        = render :partial => 'posts/smiles'
    %tr
      %td{:colspan => 2, :align => :center}
        -# Older browsers may not support getElementById... so KISS me!
        =f.text_area 'body', :tabindex => 2, :cols => 75, :rows => 12, :onfocus => "last = document.getElementById('loginpost_body');"
    %tr
      %td{:colspan => 2, :align => :center}
        = f.submit t('helpers.submit.posts.preview'), :tabindex => 4, :default => true, :name => :preview
        = f.submit :tabindex => 3
    %tr
      %td{:colspan => 2, :align => :center}
        -# Display captcha
        - if !current_user && captcha_enabled
          =t :'recaptcha.prompt'
          = captcha_tags

app/views/posts/_posts.html.haml
- content_for(:title) {": #{@post.htmlsafe_title}".html_safe}
%div#mainpost
  %div.post-intro
    %div.tools
      -# Check for persistence: we can't perform any of the actions on posts that are not saved (in preview, for instance)
      - if @post.persisted?
        -# Post Editing link (moved here from index to make it faster)
        - if permitted_to? :edit, @post
          = link_to t("Edit"), edit_post_path(@post)
          %br/
        - else
          =ta(:cant_edit,:post)
        -# Pazuzuing
        - if permitted_to? :new, :pazuzus
          -#Note that :host is a reserved key!
          = link_to ta(:create,'pazuzu'), new_user_pazuzu_path(current_user, :bastard => @post.user, :unreg_name => @post.unreg_name, :post_host => @post.host)
        -# Moderation
        - if permitted_to? :remove, @post
          = link_to t('moderation.spam.button'), remove_post_path(@post), :confirm => t('moderation.spam.confirm')
    - if @post.persisted?
      = ta(:header,:post)
      = link_to "\##{@post.id}", post_path(@post)
      -if @post.deleted
        %span.deleted-mark=ta(:deleted,:post)
      -if imp = @post.import
        \//
        %span.imported-mark
          =ta('imported.source',:post)
          = link_to "\##{imp.back}", "#{sprintf imp.source.template, imp.back}"
          =ta('imported.from',:post)
          = link_to imp.source.url, imp.source.url
        \//
    %div.author
      =ta(:sent_by,:post)
      - user_link @post.user, @post.unreg_name
      %small="(#{@post.host})"
      - if @post.persisted?
        =t("at")
        ="#{user_time @post.created_at}."
        -if @post.created_at != @post.edited_at
          %span.edited-at
            =ta(:last_edit,:post)
            ="#{user_time @post.edited_at}"
            - if editor = @post.last_editor
              =ta(:last_edit_by,:post)
              -user_link editor
  %div.post-title
    != @post.filtered_title
  %div.post-body
    -# Note that we do not strip the post in DB, but rather do it in the view
    - unless (pb = @post.filtered_body.strip).blank?
      %hr/
      !=pb
  =render 'posts/signature'

app/views/posts/_signature.html.haml
-if @post.user
  -signature = @post.user.formatted_signature
  -unless signature.blank?
    %div.signature
      -if current_presentation.hide_signatures
        %div.no=t :signatures_are_hidden
      -else
        !=signature

app/views/posts/_sourcepost.html.haml
-# the name of the form is used in post.js tag editor!  Do not change!
%iframe{:src => post_iframe_source_path(@source,@source_reply_to), :seamless => true, :width => '100%', :height => 500, :frameborder => 0, :name => 'source_reply'}
:javascript
  waitForSourcePost_Crippled('source_reply','#{escape_javascript my_reply_to_source_path(@source,@source_reply_to)}','#{escape_javascript instant_source_path(@source)}');

app/views/posts/_subtree.html.haml
-# coding: utf-8
-# To improve performance, you must supply thread to this partial
- thr = @thread || thread
- return unless thr && thr.fast_head
- if defined?(fast) && fast
  - buf = ''
  -# 'start' post is nil, which means we display the whole thread.  We save a DB request by not fetching it!
  != fast_tree_cache(thr,buf,nil,thr.presentation || current_presentation)
-else
  -if post
    = render :partial => 'posts/header_line', :locals => {:post => post, :thr => thr}
    -# TODO: this partial and heder_line compute the "hidden" two times.  This may be optimized
    -#We only hide posts in the index, hence @show_all_posts condition!
    - if post.hidden_by?(:user => current_user, :thread_hides => thr.hides) && !@show_all_posts
      %span.modifier=t("hidden")
    - else
      -# Only build subtree if it's not hidden
      - subtree = thr.build_subtree unless defined?(subtree) && subtree
      - children = subtree[post.id] || []
      - unless children.empty?
        %div.post-children
          %ul
            - children.each do |child|
              %li= render :partial => 'posts/subtree', :locals => {:post => child, :subtree => subtree, :thread => thr}

app/views/posts/edit.html.haml
%h1=ta(:edit,:post)

=render @post
=render 'signature'

%div
  = render :partial => 'form'

%div.threads
  = render :partial => 'subtree', :locals => {:post => @thread.head}

app/views/posts/latest.html.haml
%h1=ta(:latest,:post)
%ul
  - presentation = current_presentation
  - @posts.each do |p|
    - unless_deleted p do
      %li
        != fast_tree_presentation('',{},p,{},presentation)

app/views/posts/show.html.haml
=render @post
%div.after-post
  %div.threads
    = render :partial => 'subtree', :locals => {:post => @thread.head, :fast => true}
  -unless @post.deleted
    -if @source
      %div
        = render :partial => 'sourcepost'
        = link_to t('reply_locally'), post_path(@post, :source => 'here')
    -else
      %div
        = render :partial => 'loginpost'
        = link_to t('reply_to_source'), post_path(@post)
  -else
    %div.hint
      =ta('noreply.deleted',:post)

app/views/posts/sourcepost_iframe.html.haml
%html
  %head
    %meta{:content=>"text/html; charset=windows-1251", 'http-equiv'=>"Content-Type"}
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = javascript_include_tag "posts"
  %body
    %form{ :action => @source.reply_to_post_url(@source_reply_to), :method => :post, :name => 'postform'}
      -# Now the form itself
      %table{:border=>0, :cellspacing => 0, :cellpadding => 3, :align => 'center'}
        -# Do not show "reply to" if we are creating a new thread
        -if @source_reply_to
          %tr
            %td{:colspan => 2, :align => "center"}
              %big
                %a{:name => 'reply'}
                  =label_tag t('activemodel.attributes.loginpost.reply_into')
                  =link_to @source.name, @source.url
                  -if @import
                    =label_tag t('activemodel.attributes.loginpost.to_post')
                    =link_to "\##{@import.back}", "#{sprintf @import.source.template, @import.back}"
                  -else
                    =label_tag t('activemodel.attributes.loginpost.new_thread')
          %tr
            %td{:colspan => 2}
              %hr{:align => 'center', :width => '80%', :noshade => true}
        %tr
          %td{:align => 'left', :colspan => 2, :width => 600}
            =t('external_credentials')
            -#=link_to t('reply_locally'), '?source=here'
        %tr
          %td{:align => 'center'}=label_tag t('activemodel.attributes.loginpost.title')
          %td
            =text_field_tag 'subject', '', :size => 88, :tabindex => 1
        %tr
          %td{:colspan => 2, :class => 'toolbar', :align=>'center'}
            - buttons = [%w(b i u q pic url h s sup sub strike), %w(color red pre center tex tub spoiler hr smile)]
            - buttons.each do |row|
              - row.each do |btn|
                - make_button(btn)
              %br/
            = render :partial => 'posts/smiles'
        %tr
          %td{:colspan => 2, :align => :center}
            -# Older browsers may not support getElementById... so KISS me!
            =text_area_tag 'body', '', :tabindex => 2, :cols => 75, :rows => 12, :onfocus => "last = document.getElementById('body');"
        %tr
          %td{:colspan => 2, :align => :center}
            = submit_tag t('helpers.submit.posts.preview'), :tabindex => 4, :default => true, :name => :preview, :disabled => true
            = submit_tag t('helpers.submit.loginpost.create'), :tabindex => 3, :name => 'post'#, :onclick => 'this.disabled=true'

app/views/posts/toggle_like.js.erb
<%
  buf = ''
  # HTML comes escaped out of our renderer, we don't need this since we pass it via JS
  thread_html = fast_tree_cache(@thread,buf,nil,current_presentation).html_safe

  # NOTE the additional <body> tag.  This is to easen the selection of the node that otherwise would've been root in the returned HTML.
%>
replace_postline_with(<%= @post.id %>, '<div> <%= j thread_html %> </div>');

app/views/posts/toggle_showhide.js.erb
<%
  buf = ''
  # HTML comes escaped out of our renderer, we don't need this since we pass it via JS
  thread_html = fast_tree_cache(@thread,buf,nil,current_presentation).html_safe

  # NOTE the additional <body> tag.  This is to easen the selection of the node that otherwise would've been root in the returned HTML.
%>
replace_subthread_with(<%= @post.id %>, '<div> <%= j thread_html %> </div>');